version: 0.2
phases:
  pre_build:
    commands:
      - REGION=ap-northeast-1
      - REGISTRY=${ECR_REPO_URI%/*}
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$REGISTRY"
  build:
    commands:
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $ECR_REPO_URI:$IMAGE_TAG
